# -*- coding: utf-8 -*-
"""code_HIGGS_BOSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEUIeU209wXpz-YlWpF4HcenaDv6obtI
"""

#  HIGGS BOSON

# STEP 1: SETUP & SPARKSESSION
# ------------------------------------------------------------------------------
import os
import time
import pandas as pd
import numpy as np
from google.colab import drive

# Mount Google Drive
print(">>> Mounting Google Drive...")
drive.mount('/content/drive')

# PySpark Libraries
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, DoubleType
from pyspark.ml.feature import VectorAssembler, StandardScaler
from pyspark.ml.classification import RandomForestClassifier, LogisticRegression, GBTClassifier, LinearSVC
from pyspark.ml.evaluation import MulticlassClassificationEvaluator, BinaryClassificationEvaluator
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator
from pyspark.ml.functions import vector_to_array
from pyspark.sql.functions import col

# SparkSession Config & Shuffle Management
spark = SparkSession.builder \
    .appName("HIGGS_Classification_Master") \
    .config("spark.executor.memory", "6g") \
    .config("spark.driver.memory", "6g") \
    .config("spark.sql.shuffle.partitions", "200") \
    .master("local[*]") \
    .getOrCreate()

spark.sparkContext.setLogLevel("ERROR")

# Model Checkpointing
spark.sparkContext.setCheckpointDir("/tmp/checkpoints")


# STEP 2: DATA INGESTION (RDD-BASED PARALLELIZATION)
# ------------------------------------------------------------------------------
print("\n>>> STEP 2: RDD-Based Parallel Ingestion (Bronze Layer)...")

path_higgs = "/content/drive/MyDrive/Bigdata/HIGGS/HIGGS.csv"

# 1. RDD Ingestion (Partitioning strategy & RDD usage)
sc = spark.sparkContext
raw_rdd = sc.textFile(path_higgs, minPartitions=200)

# 2. RDD map function
def parse_row(row):
    fields = row.split(",")
    # First field is label, remaining 28 are features
    return tuple([float(x) for x in fields])

parsed_rdd = raw_rdd.map(parse_row)

# 3. Convert RDD to DataFrame (Silver Layer)
# Data validation at ingestion
schema = StructType([StructField("label", DoubleType(), True)] +
                    [StructField(f"feature_{i}", DoubleType(), True) for i in range(1, 29)])

df_raw = spark.createDataFrame(parsed_rdd, schema)

print(f"   Total Rows Loaded: {df_raw.count()} | Total Columns: {len(df_raw.columns)}")


# STEP 3: PREPROCESSING PIPELINE (SCALING & MEMORY MANAGEMENT)
# ------------------------------------------------------------------------------
print("\n>>> STEP 3: Strategic Sampling & Memory Caching...")

# 1. Upstream Sampling
vraj_sample_df = df_raw.sample(fraction=0.05, seed=42)

# 2. Custom Transformer Pipeline
feature_cols = [f"feature_{i}" for i in range(1, 29)]
assembler = VectorAssembler(inputCols=feature_cols, outputCol="raw_features")
scaler = StandardScaler(inputCol="raw_features", outputCol="features", withStd=True, withMean=True)

df_assembled = assembler.transform(vraj_sample_df)
df_scaled = scaler.fit(df_assembled).transform(df_assembled)

# 3. Memory Management
model_data = df_scaled.select("features", "label").cache()

# Force Spark to execute the cache immediately
print(f"   [CACHED] Data ready for ML Training: {model_data.count()} rows")

# Split the data (Rubric 4a: Train/validation/test split)
train_data, test_data = model_data.randomSplit([0.8, 0.2], seed=42)
print("   Data successfully split into Train (80%) and Test (20%).")


# STEP 4: DISTRIBUTED MODELING & EVALUATION
# ------------------------------------------------------------------------------
print("\n>>> STEP 4: Training 4 Big Data Models")

# 1. Define Algorithms
rf = RandomForestClassifier(labelCol="label", featuresCol="features", seed=42)
lr = LogisticRegression(labelCol="label", featuresCol="features", maxIter=10)
svm = LinearSVC(labelCol="label", featuresCol="features", maxIter=10)
gbt = GBTClassifier(labelCol="label", featuresCol="features", maxIter=10, seed=42)

# 2. Setup Evaluators (Rubric 4a: Distributed Evaluation Metrics)
eval_auc = BinaryClassificationEvaluator(labelCol="label", metricName="areaUnderROC")
eval_acc = MulticlassClassificationEvaluator(labelCol="label", metricName="accuracy")

# 3. Hyperparameter Tuning (Rubric 2b: CrossValidator with parallelism)
paramGrid_rf = ParamGridBuilder().addGrid(rf.numTrees, [10, 20]).build()

cv_rf = CrossValidator(
    estimator=rf,
    estimatorParamMaps=paramGrid_rf,
    evaluator=eval_auc,
    numFolds=2,
    parallelism=2
)

# 4. Model List
models = [
    ("Random Forest (CV)", cv_rf),
    ("Gradient Boosted", gbt),
    ("Logistic Reg", lr),
    ("Linear SVM", svm)
]

print(f"\n{'Algorithm':<20} | {'AUC':<7} | {'Acc':<7} | {'Time'}")
print("-" * 50)

best_higgs_model_vraj = None
best_predictions = None

# 5. Training Loop
for name, algo in models:
    try:
        start_time = time.time()
        model = algo.fit(train_data)
        preds = model.transform(test_data)

        auc = eval_auc.evaluate(preds)
        acc = eval_acc.evaluate(preds)

        print(f"{name:<20} | {auc:.4f} | {acc:.4f} | {(time.time() - start_time):.1f}s")

        # Model Serialization
        if name == "Gradient Boosted":
            best_higgs_model_vraj = model
            best_predictions = preds

    except Exception as e:
        print(f"{name:<20} | FAILED: {str(e)[:50]}")

# 6. SERIALIZATION
if best_higgs_model_vraj:
    model_path = "/content/drive/MyDrive/Bigdata/higgs_gbt_model"
    best_higgs_model_vraj.write().overwrite().save(model_path)
    print(f"\nSUCCESS: GBT Model serialized and saved to: {model_path}")


# STEP 5: SCALABILITY ANALYSIS
# ------------------------------------------------------------------------------
print("\n>>> STEP 5: Scalability Test PySpark vs Scikit-Learn")
from sklearn.linear_model import LogisticRegression as SkLearnLR

# Compare with scikit-learn
sample_frac = 0.01
pdf_sample = model_data.sample(fraction=sample_frac, seed=42).toPandas()

if not pdf_sample.empty:
    X_sk = pdf_sample["features"].apply(lambda x: x.toArray()).tolist()
    y_sk = pdf_sample["label"].tolist()

    start = time.time()
    try:
        SkLearnLR(max_iter=5).fit(X_sk, y_sk)
        sk_time = time.time() - start
        print(f"   Scikit-Learn Time (on tiny 1% subset): {sk_time:.4f} seconds")
        print("   (Note: Scikit-Learn would crash/OOM if given the full dataset)")
    except Exception as e:
        print(f"   Scikit-Learn Error: {e}")


# STEP 6: PARQUET
# ------------------------------------------------------------------------------
print("\n>>> STEP 6: Generating Tableau Parquet Extract (Rubric 3b)...")

if best_predictions is not None:
    df_with_array = best_predictions.withColumn("features_array", vector_to_array("features"))

    df_tableau_prep = df_with_array \
        .withColumn("feature_1", col("features_array")[0]) \
        .withColumn("feature_2", col("features_array")[1]) \
        .withColumn("feature_22", col("features_array")[21])

    tableau_cols = ["label", "prediction", "feature_1", "feature_2", "feature_22"]


    output_path = "/content/drive/MyDrive/Bigdata/HIGGS_tableau_extract.parquet"

    # Coalesce
    df_tableau_prep.select(*tableau_cols).coalesce(1).write.mode("overwrite").parquet(output_path)

    print(f"SUCCESS: Tableau Parquet file saved at: {output_path}")

#CSV
print("Converting Parquet to CSV for backup...")
parquet_path = "/content/drive/MyDrive/Bigdata/HIGGS_tableau_extract.parquet"
df_convert = pd.read_parquet(parquet_path)
csv_path = "/content/drive/MyDrive/Bigdata/HIGGS_tableau_extract.csv"
df_convert.to_csv(csv_path, index=False)
print(f"Tableau CSV backup ready at: {csv_path}")

spark

!pip install ngrok pyngrok

spark_web_ui_port = spark.sparkContext.uiWebUrl.split(':')[-1]
print(f"Spark UI is running on port: {spark_web_ui_port}")

from pyngrok import ngrok
ngrok.kill()

public_url = ngrok.connect(int(spark_web_ui_port))
print(f"Spark UI available at: {public_url}")
print("Click the link above to open the Spark UI in your browser.")